Repository BOA-with-elephant/Header-backend, pull requests merged in 2025-07, with the labels that each got.

#2 [CREATE] JPA 엔티티 및 MySQL 연동 완료
  src/main/java/com/header/header/config/BeanConfig.java
  src/main/java/com/header/header/domain/menu/entity/Menu.java
  src/main/java/com/header/header/domain/menu/entity/MenuCategory.java
  src/main/java/com/header/header/domain/message/enitity/MessageTemplate.java
  src/main/java/com/header/header/domain/reservation/entity/Reservation.java
  src/main/java/com/header/header/domain/sales/entity/Sales.java
  src/main/java/com/header/header/domain/shop/enitity/Shop.java
  src/main/java/com/header/header/domain/shop/enitity/ShopCategory.java
  src/main/java/com/header/header/domain/shop/enitity/ShopMessageHistory.java
  src/main/java/com/header/header/domain/user/enitity/User.java
  src/main/java/com/header/header/domain/visitors/enitity/Visitors.java
Labels: enhancement

#15 [FEATURE] #12 MenuCategory CRUD 구현
  src/main/java/com/header/header/config/BeanConfig.java
  src/main/java/com/header/header/domain/menu/dto/MenuCategoryDTO.java
  src/main/java/com/header/header/domain/menu/entity/MenuCategory.java
  src/main/java/com/header/header/domain/menu/entity/MenuCategoryId.java
  src/main/java/com/header/header/domain/menu/repository/MenuCategoryRepository.java
  src/main/java/com/header/header/domain/menu/service/MenuCategoryService.java
  src/test/java/com/header/header/domain/menu/MenuCategoryRepositoryTests.java
Labels: enhancement

#16 [FEATURE] #7 MessageTemplate CRUD 구현
  src/main/java/com/header/header/domain/message/dto/MessageTemplateDTO.java
  src/main/java/com/header/header/domain/message/dto/PlaceholderDTO.java
  src/main/java/com/header/header/domain/message/enitity/MessageTemplate.java
  src/main/java/com/header/header/domain/message/enums/MessagePlaceholder.java
  src/main/java/com/header/header/domain/message/enums/TemplateType.java
  src/main/java/com/header/header/domain/message/exception/InvalidTemplateException.java
  src/main/java/com/header/header/domain/message/exception/ValidationResult.java
  src/main/java/com/header/header/domain/message/repository/MessageTemplateRepository.java
  src/main/java/com/header/header/domain/message/service/MessageTemplateService.java
  src/main/java/com/header/header/domain/message/validator/TemplateValidator.java
  src/test/java/com/header/header/domain/message/service/MessageTemplateServiceTests.java
Labels: enhancement

#26 [FEATURE] #20 Shop CRUD 구현 - MapAPI 기능 완료
  src/main/java/com/header/header/domain/reservation/dto/UserReservationDTO.java
  src/main/java/com/header/header/domain/reservation/entity/Reservation.java
  src/main/java/com/header/header/domain/reservation/enums/UserReservationErrorCode.java
  src/main/java/com/header/header/domain/reservation/service/UserReservationService.java
  src/main/java/com/header/header/domain/shop/converter/ShopStatusConverter.java
  src/main/java/com/header/header/domain/shop/dto/MapServiceDTO.java
  src/main/java/com/header/header/domain/shop/dto/ShopSummaryDTO.java
  src/main/java/com/header/header/domain/shop/dto/ShopUpdateDTO.java
  src/main/java/com/header/header/domain/shop/entity/Shop.java
  src/main/java/com/header/header/domain/shop/enums/ShopErrorCode.java
  src/main/java/com/header/header/domain/shop/enums/ShopStatus.java
  src/main/java/com/header/header/domain/shop/exception/ShopExceptionHandler.java
  src/main/java/com/header/header/domain/shop/external/MapService.java
  src/main/java/com/header/header/domain/shop/repository/ShopRepository.java
  src/main/java/com/header/header/domain/shop/repository/UserRepository.java
  src/main/java/com/header/header/domain/shop/service/ShopService.java
  src/test/java/com/header/header/domain/reservation/service/UserReservationTests.java
  src/test/java/com/header/header/domain/shop/service/ShopServiceTest.java
Labels: enhancement

#28 [FEAT] #11 Menu CRUD 구현 및 [FIX] #27 Menu Category 예외 처리 개선
  src/main/java/com/header/header/common/exception/ErrorResponse.java
  src/main/java/com/header/header/common/exception/GlobalExceptionHandler.java
  src/main/java/com/header/header/common/exception/NotFoundException.java
  src/main/java/com/header/header/config/BeanConfig.java
  src/main/java/com/header/header/domain/menu/dto/MenuCategoryDTO.java
  src/main/java/com/header/header/domain/menu/dto/MenuDTO.java
  src/main/java/com/header/header/domain/menu/entity/Menu.java
  src/main/java/com/header/header/domain/menu/repository/MenuRepository.java
  src/main/java/com/header/header/domain/menu/service/MenuCategoryService.java
  src/main/java/com/header/header/domain/menu/service/MenuService.java
  src/test/java/com/header/header/domain/menu/service/MenuCategoryServiceTests.java
  src/test/java/com/header/header/domain/menu/service/MenuServiceTests.java
Labels: enhancement, wontfix

#31 [FEATURE] #5 AdminReservation CRUD 구현
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/header/header/domain/reservation/dto/BasicReservationDTO.java
  src/main/java/com/header/header/domain/reservation/dto/BossReservationDTO.java
  src/main/java/com/header/header/domain/reservation/dto/BossResvInputDTO.java
  src/main/java/com/header/header/domain/reservation/dto/BossResvMenuCategoryDTO.java
  src/main/java/com/header/header/domain/reservation/dto/BossResvMenuDTO.java
  src/main/java/com/header/header/domain/reservation/dto/BossResvUserDTO.java
  src/main/java/com/header/header/domain/reservation/entity/BossReservation.java
  src/main/java/com/header/header/domain/reservation/entity/BossResvMenu.java
  src/main/java/com/header/header/domain/reservation/entity/BossResvMenuCategory.java
  src/main/java/com/header/header/domain/reservation/entity/Reservation.java
  src/main/java/com/header/header/domain/reservation/repository/BossReservationRepository.java
  src/main/java/com/header/header/domain/reservation/service/BossReservationService.java
  src/main/java/com/header/header/domain/user/dto/UserDTO.java
  src/main/java/com/header/header/domain/user/repository/MainUserRepository.java
  src/test/java/com/header/header/domain/reservation/repository/BossReservationRepositoryTests.java
Labels: enhancement

#38 [FEATURE] #8 ShopMessageBatch, ShopMessageHistroy CRUD 설계 및 ShopMessageBatch CRUD 구현 완료
  src/main/java/com/header/header/domain/message/dto/MessageSendBatchDTO.java
  src/main/java/com/header/header/domain/message/dto/ShopMessageHistoryDTO.java
  src/main/java/com/header/header/domain/message/entity/MessageSendBatch.java
  src/main/java/com/header/header/domain/message/entity/MessageTemplate.java
  src/main/java/com/header/header/domain/message/entity/ShopMessageHistory.java
  src/main/java/com/header/header/domain/message/exception/InvalidBatchException.java
  src/main/java/com/header/header/domain/message/projection/MessageBatchListView.java
  src/main/java/com/header/header/domain/message/projection/MessageContentView.java
  src/main/java/com/header/header/domain/message/projection/MessageHistoryListView.java
  src/main/java/com/header/header/domain/message/repository/MessageSendBatchRepository.java
  src/main/java/com/header/header/domain/message/repository/MessageTemplateRepository.java
  src/main/java/com/header/header/domain/message/service/MessageSendBatchService.java
  src/main/java/com/header/header/domain/message/service/MessageTemplateService.java
  src/main/java/com/header/header/domain/message/service/ShopMessageHistoryService.java
  src/main/java/com/header/header/domain/shop/entity/ShopMessageHistory.java
  src/test/java/com/header/header/domain/message/service/MessageSendBatchTests.java
Labels: enhancement

#37 [Hotfix] #35 중복 체크 상세 적용
  src/main/java/com/header/header/domain/auth/common/ApiResponse.java
  src/main/java/com/header/header/domain/auth/model/service/AuthUserService.java
  src/test/java/com/header/header/domain/auth/AuthUserServiceTests.java
Labels: enhancement

#46 [FEATURE] #30 ShopMessageHistory CRUD 구현 완료
  src/main/java/com/header/header/domain/message/dto/ShopMessageHistoryDTO.java
  src/main/java/com/header/header/domain/message/entity/ShopMessageHistory.java
  src/main/java/com/header/header/domain/message/enums/MessageStatus.java
  src/main/java/com/header/header/domain/message/projection/MessageBatchListView.java
  src/main/java/com/header/header/domain/message/projection/MessageHistoryListView.java
  src/main/java/com/header/header/domain/message/repository/ShopMessageHistoryRepository.java
  src/main/java/com/header/header/domain/message/service/ShopMessageHistoryService.java
  src/test/java/com/header/header/domain/message/service/ShopMessageHistoryTests.java
Labels: enhancement

#50 [FIX] #48 BossReservation, UserReservation Entity 통합 및 수정
  src/main/java/com/header/header/domain/menu/entity/Menu.java
  src/main/java/com/header/header/domain/reservation/converter/ReservationStateConverter.java
  src/main/java/com/header/header/domain/reservation/dto/BossResvMenuDTO.java
  src/main/java/com/header/header/domain/reservation/dto/BossResvUserDTO.java
  src/main/java/com/header/header/domain/reservation/dto/UserReservationDTO.java
  src/main/java/com/header/header/domain/reservation/entity/BossReservation.java
  src/main/java/com/header/header/domain/reservation/entity/Reservation.java
  src/main/java/com/header/header/domain/reservation/enums/ReservationState.java
  src/main/java/com/header/header/domain/reservation/projection/UserReservationSummary.java
  src/main/java/com/header/header/domain/reservation/repository/BossReservationRepository.java
  src/main/java/com/header/header/domain/reservation/repository/UserReservationRepository.java
  src/main/java/com/header/header/domain/reservation/service/BossReservationService.java
  src/main/java/com/header/header/domain/reservation/service/UserReservationService.java
  src/main/java/com/header/header/domain/user/entity/User.java
  src/test/java/com/header/header/domain/reservation/repository/BossReservationRepositoryTests.java
  src/test/java/com/header/header/domain/reservation/service/UserReservationTests.java
Labels: enhancement

#52 [HOTFIX] UserReservation Repository 복구
  src/main/java/com/header/header/domain/reservation/repository/UserReservationRepository.java
  src/main/java/com/header/header/domain/reservation/service/BossReservationService.java
  src/main/java/com/header/header/domain/reservation/service/UserReservationService.java
Labels: bug

#56 [FEATURE] #55 Read ShopUserList 구현
  src/main/java/com/header/header/domain/visitors/DTO/VisitorDetailDTO.java
  src/main/java/com/header/header/domain/visitors/DTO/VisitorsDTO.java
  src/main/java/com/header/header/domain/visitors/enitity/Visitors.java
  src/main/java/com/header/header/domain/visitors/projection/UserFavoriteMenuView.java
  src/main/java/com/header/header/domain/visitors/projection/VisitStatisticsView.java
  src/main/java/com/header/header/domain/visitors/projection/VisitorWithUserInfoView.java
  src/main/java/com/header/header/domain/visitors/repository/VisitorsRepository.java
  src/main/java/com/header/header/domain/visitors/service/VisitorsService.java
  src/test/java/com/header/header/domain/visitors/service/VisitorsTests.java
Labels: enhancement

#60 [FEATURE] #59 feature create user 기능 구현
  src/main/java/com/header/header/domain/user/service/UserService.java
  src/main/java/com/header/header/domain/visitors/DTO/VisitorsDTO.java
  src/main/java/com/header/header/domain/visitors/service/VisitorsService.java
  src/test/java/com/header/header/domain/visitors/service/VisitorsTests.java
Labels: enhancement

#61 [FIX] #53 Shop CRUD 기능 구현 완료
  src/main/java/com/header/header/domain/shop/dto/MapServiceDTO.java
  src/main/java/com/header/header/domain/shop/dto/ShopCreationDTO.java
  src/main/java/com/header/header/domain/shop/dto/ShopSearchConditionDTO.java
  src/main/java/com/header/header/domain/shop/dto/ShopSummaryResponseDTO.java
  src/main/java/com/header/header/domain/shop/dto/ShopUpdateDTO.java
  src/main/java/com/header/header/domain/shop/entity/Shop.java
  src/main/java/com/header/header/domain/shop/enums/ShopErrorCode.java
  src/main/java/com/header/header/domain/shop/enums/ShopStatus.java
  src/main/java/com/header/header/domain/shop/projection/ShopDetailResponse.java
  src/main/java/com/header/header/domain/shop/projection/ShopSummary.java
  src/main/java/com/header/header/domain/shop/repository/ShopCategoryRepository.java
  src/main/java/com/header/header/domain/shop/repository/ShopRepository.java
  src/main/java/com/header/header/domain/shop/service/ShopService.java
  src/test/java/com/header/header/domain/shop/service/ShopServiceTest.java
Labels: enhancement

#62 [FEATURE] #13 Shop Category Read 기능 완료
  src/main/java/com/header/header/domain/shop/dto/ShopCategoryDTO.java
  src/main/java/com/header/header/domain/shop/repository/ShopCategoryRepository.java
  src/main/java/com/header/header/domain/shop/service/ShopCategoryService.java
  src/test/java/com/header/header/domain/shop/service/ShopCategoryServiceTest.java
Labels: enhancement

#63 [FIX] #54 User Reservation Create, Read, Delete 기능 완료
  src/main/java/com/header/header/domain/menu/repository/MenuRepository.java
  src/main/java/com/header/header/domain/reservation/dto/UserReservationDTO.java
  src/main/java/com/header/header/domain/reservation/dto/UserReservationSearchConditionDTO.java
  src/main/java/com/header/header/domain/reservation/entity/BossReservation.java
  src/main/java/com/header/header/domain/reservation/enums/UserReservationErrorCode.java
  src/main/java/com/header/header/domain/reservation/projection/UserReservationDetail.java
  src/main/java/com/header/header/domain/reservation/projection/UserReservationSummary.java
  src/main/java/com/header/header/domain/reservation/repository/UserReservationRepository.java
  src/main/java/com/header/header/domain/reservation/service/BossReservationService.java
  src/main/java/com/header/header/domain/reservation/service/UserReservationService.java
  src/test/java/com/header/header/domain/reservation/service/UserReservationTests.java
Labels: enhancement

#66 [FEATURE][FIX] #44 Add Noshow And Refactoring ReservationEntity
  src/main/java/com/header/header/domain/menu/repository/MenuRepository.java
  src/main/java/com/header/header/domain/reservation/converter/ReservationStateConverter.java
  src/main/java/com/header/header/domain/reservation/dto/BossReservationDTO.java
  src/main/java/com/header/header/domain/reservation/dto/BossResvInputDTO.java
  src/main/java/com/header/header/domain/reservation/dto/BossResvMenuDTO.java
  src/main/java/com/header/header/domain/reservation/dto/BossResvProjectionDTO.java
  src/main/java/com/header/header/domain/reservation/dto/BossResvUserDTO.java
  src/main/java/com/header/header/domain/reservation/entity/BossReservation.java
  src/main/java/com/header/header/domain/reservation/entity/Reservation.java
  src/main/java/com/header/header/domain/reservation/projection/BossResvDetailView.java
  src/main/java/com/header/header/domain/reservation/repository/BossReservationRepository.java
  src/main/java/com/header/header/domain/reservation/service/BossReservationService.java
  src/main/java/com/header/header/domain/shop/entity/Shop.java
  src/test/java/com/header/header/domain/reservation/repository/BossReservationRepositoryTests.java
Labels: enhancement

#70 Feature/58 feature updatedelete shopuser 기능 구현
  src/main/java/com/header/header/domain/visitors/enitity/Visitors.java
  src/main/java/com/header/header/domain/visitors/repository/VisitorsRepository.java
  src/main/java/com/header/header/domain/visitors/service/VisitorsService.java
  src/test/java/com/header/header/domain/visitors/service/VisitorsTests.java
Labels: enhancement

#80 [FEATURE] #77 Shop Holiday CRUD 기능 구현 완료
  src/main/java/com/header/header/domain/reservation/repository/UserReservationRepository.java
  src/main/java/com/header/header/domain/reservation/service/UserReservationService.java
  src/main/java/com/header/header/domain/shop/dto/HolCreationDTO.java
  src/main/java/com/header/header/domain/shop/dto/HolResDTO.java
  src/main/java/com/header/header/domain/shop/dto/HolUpdateDTO.java
  src/main/java/com/header/header/domain/shop/dto/ShopHolidayDTO.java
  src/main/java/com/header/header/domain/shop/entity/ShopHoliday.java
  src/main/java/com/header/header/domain/shop/enums/ShopHolidayErrorCode.java
  src/main/java/com/header/header/domain/shop/exception/ShopHolidayExceptionHandler.java
  src/main/java/com/header/header/domain/shop/projection/ShopHolidayInfo.java
  src/main/java/com/header/header/domain/shop/repository/ShopHolidayRepository.java
  src/main/java/com/header/header/domain/shop/service/ShopHolidayService.java
  src/test/java/com/header/header/domain/shop/service/ShopHolidayServiceTests.java
Labels: enhancement

#82 [FIX] User Reservation 예외 처리 개선 및 예약 가능 스케쥴 리스트 반환 기능 구현
  src/main/java/com/header/header/domain/reservation/dto/UserResvAvailableScheduleDTO.java
  src/main/java/com/header/header/domain/reservation/enums/UserReservationErrorCode.java
  src/main/java/com/header/header/domain/reservation/repository/UserReservationRepository.java
  src/main/java/com/header/header/domain/reservation/service/UserReservationService.java
  src/main/java/com/header/header/domain/shop/repository/ShopHolidayRepository.java
  src/test/java/com/header/header/domain/reservation/service/UserReservationTests.java
Labels: enhancement

#87 [FEATURE] Send Message Immediately Facade
  build.gradle
  src/main/java/com/header/header/config/AsyncConfig.java
  src/main/java/com/header/header/config/CoolSmsApiConfig.java
  src/main/java/com/header/header/domain/message/dto/MessageRequest.java
  src/main/java/com/header/header/domain/message/dto/MessageResponse.java
  src/main/java/com/header/header/domain/message/dto/MessageSendBatchDTO.java
  src/main/java/com/header/header/domain/message/dto/ShopMessageHistoryDTO.java
  src/main/java/com/header/header/domain/message/entity/ShopMessageHistory.java
  src/main/java/com/header/header/domain/message/external/coolsms/CoolSmsService.java
  src/main/java/com/header/header/domain/message/service/MessageAsyncService.java
  src/main/java/com/header/header/domain/message/service/ShopMessageHistoryService.java
  src/main/java/com/header/header/domain/user/repository/MainUserRepository.java
  src/main/java/com/header/header/domain/user/service/UserService.java
  src/test/java/com/header/header/domain/message/service/MessageAsyncServiceTest.java
  src/test/java/com/header/header/domain/message/service/MessageIntergrationTest.java
  src/test/java/com/header/header/domain/message/service/ShopMessageHistoryTests.java
Labels: enhancement

#92 [BUG] #91 bug 프론트앤드 api 요청시 401 unauthorized 해결
  src/main/java/com/header/header/auth/config/SecurityConfig.java
Labels: bug

#98 [FIX] #97 매출관리를 위한 DTO 필드 및 조회 쿼리 개선
  src/main/java/com/header/header/domain/sales/controller/SalesController.java
  src/main/java/com/header/header/domain/sales/dto/SalesDetailDTO.java
  src/main/java/com/header/header/domain/sales/repository/SalesRepository.java
  src/main/java/com/header/header/domain/sales/service/SalesService.java
Labels: wontfix

#132 [HOTFIX] #131 change api path /myshop → /my shops (sales/menu)
  src/main/java/com/header/header/domain/menu/controller/MenuCategoryController.java
  src/main/java/com/header/header/domain/menu/controller/MenuController.java
  src/main/java/com/header/header/domain/sales/controller/SalesController.java
Labels: wontfix

#134 [FEATURE] #119 BossReservation Update Reservation Info
  src/main/java/com/header/header/auth/config/SecurityConfig.java
  src/main/java/com/header/header/domain/reservation/controller/BossReservationController.java
  src/main/java/com/header/header/domain/reservation/controller/UserReservationController.java
  src/main/java/com/header/header/domain/reservation/dto/ReservationDateAndTimeDTO.java
  src/main/java/com/header/header/domain/reservation/repository/UserReservationRepository.java
  src/main/java/com/header/header/domain/reservation/service/UserReservationService.java
Labels: enhancement

#136 [FEATURE] #135 BossReservation Soft Delete
  src/main/java/com/header/header/domain/reservation/controller/BossReservationController.java
  src/main/java/com/header/header/domain/reservation/repository/UserReservationRepository.java
  src/main/java/com/header/header/domain/reservation/service/UserReservationService.java
Labels: enhancement

#137 [FEATURE] 사장님 Shop 관리 및 휴일 관리 컨트롤러 매핑
  src/main/java/com/header/header/domain/reservation/controller/UserReservationController.java
  src/main/java/com/header/header/domain/reservation/repository/UserReservationRepository.java
  src/main/java/com/header/header/domain/shop/controller/AdminShopController.java
  src/main/java/com/header/header/domain/shop/controller/ShopCategoryController.java
  src/main/java/com/header/header/domain/shop/controller/ShopController.java
  src/main/java/com/header/header/domain/shop/controller/ShopHolidayController.java
  src/main/java/com/header/header/domain/shop/dto/HolCreationDTO.java
  src/main/java/com/header/header/domain/shop/dto/HolUpdateDTO.java
  src/main/java/com/header/header/domain/shop/projection/ShopHolidayInfo.java
  src/main/java/com/header/header/domain/shop/repository/ShopHolidayRepository.java
  src/main/java/com/header/header/domain/shop/repository/ShopRepository.java
  src/main/java/com/header/header/domain/shop/service/ShopHolidayService.java
  src/test/java/com/header/header/domain/shop/service/ShopHolidayServiceTests.java
Labels: enhancement

#141 [FEATURE] 123 feature add missing controller
  src/main/java/com/header/header/auth/config/SecurityConfig.java
  src/main/java/com/header/header/auth/model/dto/TokenDTO.java
  src/main/java/com/header/header/auth/model/service/AuthUserService.java
  src/main/java/com/header/header/domain/user/controller/UserController.java
  src/main/java/com/header/header/domain/user/service/UserFacadeService.java
  src/test/java/com/header/header/domain/user/service/UserFacadeServiceTests.java
Labels: bug

#144 [HOTFIX] #143 hotfix 수신자 메세지 세부 조회 응답 dto historycode 필드 누락
  src/main/java/com/header/header/domain/message/dto/MessageReceiver.java
  src/main/java/com/header/header/domain/message/repository/ShopMessageHistoryRepository.java
  src/main/java/com/header/header/domain/message/service/MessageHistoryService.java
  src/main/java/com/header/header/domain/message/service/MessageSendBatchService.java
Labels: duplicate

#148 Feature/145 salse create update
  src/main/java/com/header/header/domain/sales/controller/SalesController.java
  src/main/java/com/header/header/domain/sales/dto/SalesDTO.java
  src/main/java/com/header/header/domain/sales/entity/Sales.java
  src/main/java/com/header/header/domain/sales/service/SalesService.java
Labels: enhancement

#153 [FIX] #152 sales registration afterprocedure integration
  src/main/java/com/header/header/domain/sales/controller/SalesController.java
Labels: wontfix

#150 [Feature]123 feature add missing controller
  src/main/java/com/header/header/auth/config/JwtTokenProvider.java
  src/main/java/com/header/header/auth/config/SecurityConfig.java
  src/main/java/com/header/header/common/exception/GlobalExeptionHandlerForApiResponse.java
  src/main/java/com/header/header/domain/user/controller/UserController.java
Labels: enhancement

#154 [FEATURE] #142 Shop 및 User Reservation 도메인 jwt 토큰 인증 처리 추가
  src/main/java/com/header/header/auth/model/dto/LoginUserDTO.java
  src/main/java/com/header/header/domain/reservation/controller/UserReservationController.java
  src/main/java/com/header/header/domain/reservation/projection/UserReservationSummary.java
  src/main/java/com/header/header/domain/shop/common/GetUserInfoByAuthDetails.java
  src/main/java/com/header/header/domain/shop/controller/AdminShopController.java
  src/main/java/com/header/header/domain/shop/controller/ShopController.java
  src/main/java/com/header/header/domain/shop/controller/ShopHolidayController.java
  src/main/java/com/header/header/domain/shop/enums/ShopHolidayErrorCode.java
  src/main/java/com/header/header/domain/shop/service/ShopHolidayService.java
  src/main/java/com/header/header/domain/user/entity/User.java
  src/main/java/com/header/header/domain/user/projection/UserCode.java
  src/main/java/com/header/header/domain/user/repository/MainUserRepository.java
  src/test/java/com/header/header/domain/shop/service/ShopHolidayServiceTests.java
Labels: enhancement

#157 [FEATURE] #151 BossReservation Completed Procedure
  src/main/java/com/header/header/domain/reservation/controller/BossReservationController.java
  src/main/java/com/header/header/domain/reservation/service/BossReservationService.java
  src/main/java/com/header/header/domain/user/repository/MainUserRepository.java
  src/main/java/com/header/header/domain/visitors/repository/VisitorsRepository.java
  src/main/java/com/header/header/domain/visitors/service/VisitorsService.java
Labels: enhancement

#165 [MERGE] Develope 브랜치 master에 머지
  src/main/java/com/header/header/auth/config/JwtTokenProvider.java
  src/main/java/com/header/header/auth/config/SecurityConfig.java
  src/main/java/com/header/header/common/exception/GlobalExeptionHandlerForApiResponse.java
  src/main/java/com/header/header/config/AsyncConfig.java
  src/main/java/com/header/header/domain/message/controller/MessageController.java
  src/main/java/com/header/header/domain/reservation/controller/BossReservationController.java
  src/main/java/com/header/header/domain/reservation/service/BossReservationService.java
  src/main/java/com/header/header/domain/user/controller/UserController.java
  src/main/java/com/header/header/domain/user/repository/MainUserRepository.java
  src/main/java/com/header/header/domain/visitors/repository/VisitorsRepository.java
  src/main/java/com/header/header/domain/visitors/service/VisitorsService.java
Labels: wontfix
