Repository BOA-with-elephant/Header-backend, pull requests merged in 2025-08, with the labels that each got.

#167 [FIX] #166 / EDIT CI/CD
  .github/workflows/deploy.yml
  Dockerfile
  compose.yaml
  init.sql
  src/main/java/com/header/header/domain/reservation/controller/BossReservationController.java
  src/main/java/com/header/header/domain/reservation/service/BossReservationService.java
  src/main/java/com/header/header/domain/user/dto/UserDTO.java
  src/main/java/com/header/header/domain/user/entity/User.java
  src/main/java/com/header/header/domain/user/repository/MainUserRepository.java
  src/main/java/com/header/header/domain/user/service/UserService.java
  src/main/java/com/header/header/domain/visitors/repository/VisitorsRepository.java
  src/main/java/com/header/header/domain/visitors/service/VisitorsService.java
Labels: bug

#171 [FIX] #170 Add settings.gradle
  .github/workflows/deploy.yml
  .gitignore
  docker-compose.yml
  settings.gradle
  src/main/java/com/header/header/config/WebMvcConfig.java
Labels: documentation

#176 [FEATURE] #175 Add Domain Address
  src/main/java/com/header/header/auth/config/SecurityConfig.java
  src/main/java/com/header/header/config/WebMvcConfig.java
Labels: enhancement

#179 [FIX] #178 Modify Deploy.yml File
  .github/workflows/deploy.yml
Labels: bug

#184 183 fix modify cors policy
  src/main/java/com/header/header/auth/config/SecurityConfig.java
  src/main/java/com/header/header/config/WebMvcConfig.java
Labels: bug

#190 [FEATURE] #189 Add Nginx And Certbot Config
  .github/workflows/deploy.yml
  docker-compose.yml
  nginx/conf.d/default.conf
  src/main/java/com/header/header/auth/config/SecurityConfig.java
Labels: enhancement

#195 [FIX] #194 Modify Docker Compose File
  docker-compose.yml
Labels: bug

#197 [FIX] #196 Modify Dockerfile
  Dockerfile
  docker-compose.yml
Labels: bug

#199 [FIX] #198 Modify Workflows Source Code
  .github/workflows/deploy.yml
Labels: bug

#201 [Fix] #200 Modify Dockerfile And Deploy.yml
  .github/workflows/deploy.yml
  Dockerfile
Labels: bug

#203 [FIX] #202 Modify Application.yml Route
  .github/workflows/deploy.yml
  docker-compose.yml
Labels: bug

#207 [DOCUMENT] #206 Case Conversion Init.sql
  db/init.sql
Labels: bug

#213 [FEATURE] #212 BossReservation - Solving Concurrency Issues In Multithreaded Programming
  src/main/java/com/header/header/domain/reservation/controller/BossReservationController.java
  src/main/java/com/header/header/domain/reservation/projection/BossResvDetailView.java
  src/main/java/com/header/header/domain/reservation/repository/BossReservationRepository.java
  src/main/java/com/header/header/domain/reservation/service/BossReservationService.java
  src/test/java/com/header/header/domain/reservation/repository/BossReservationRepositoryTests.java
Labels: enhancement

#215 [FEATURE] #214 User Reservation API 엔드포인트 추가
  src/main/java/com/header/header/domain/reservation/controller/UserReservationController.java
  src/main/java/com/header/header/domain/reservation/projection/UserReservationForLLM.java
  src/main/java/com/header/header/domain/reservation/repository/UserReservationRepository.java
  src/main/java/com/header/header/domain/reservation/service/UserReservationService.java
  src/test/java/com/header/header/domain/reservation/service/UserReservationTests.java
Labels: enhancement

#222 [FEATURE] #220 refactor 방문자 관리 챗봇 ai 프롬프팅 및 spring api 연동 개선
  llm/app/api/visitorsbot_chat.py
  llm/app/core/settings/visitors_bot.yaml
  llm/app/main.py
  llm/app/services/visitors_service.py
  src/main/java/com/header/header/domain/visitors/controller/VisitorsController.java
  src/main/java/com/header/header/domain/visitors/repository/VisitorsRepository.java
  src/main/java/com/header/header/domain/visitors/service/VisitorsService.java
Labels: enhancement

#227 [FEATURE] #226 Add The LLM Service To The Deployment Configuration
  docker-compose.yml
  llm/Dockerfile
  llm/app/api/bossReservation_chat.py
  llm/app/main.py
  llm/gunicorn.config.py
  llm/requirements.txt
  llm/uvicorn_config.py
  nginx/conf.d/default.conf
  src/main/java/com/header/header/domain/reservation/service/ChatbotService.java
Labels: enhancement

#230 [HOTFIX] #228 응답 데이터 수정
  src/main/java/com/header/header/domain/user/controller/UserController.java
Labels: bug

#232 [HOTFIX] #231 hotfix securityconfig fix
  src/main/java/com/header/header/auth/config/SecurityConfig.java
Labels: bug

#235 [FIX\ #234 Fix Deploy Error
  .github/workflows/deploy.yml
  docker-compose.yml
  llm/Dockerfile
  llm/app/core/config.py
  llm/app/core/settings/BossReservationBot.yaml
  llm/requirements.txt
Labels: bug

#239 [FIX] #238 Fix Redis Deploy File
  .github/workflows/deploy.yml
  docker-compose.yml
  llm/Dockerfile
  llm/app/core/redis_manager.py
Labels: bug

#249 [FIX] #248 Edit Install Cryptography Command
  .github/workflows/deploy.yml
  llm/Dockerfile
  llm/requirements.txt
Labels: bug

#252 [Feature] 251 feature profile update
  src/main/java/com/header/header/auth/config/SecurityConfig.java
  src/main/java/com/header/header/auth/config/handler/LoginSuccessHandler.java
  src/main/java/com/header/header/auth/model/dto/LoginUserDTO.java
  src/main/java/com/header/header/domain/user/controller/UserController.java
Labels: enhancement

#266 [FEATURE] #265 Add Cachtools To The Requirements.txt File
  llm/requirements.txt
Labels: enhancement

#269 [FIX] #268 Change Sql Statement Case From Uppercase ToLlowercase
  src/main/java/com/header/header/domain/shop/repository/ShopRepository.java
Labels: bug

#278 [FIX] #276 Pincone Consolidate Old Session
  llm/app/services/reservation_chatbot_service.py
Labels: bug

#285 [FEAT] #282 Dynamic environment configuration for service URLs
  docker-compose.yml
  llm/app/core/config.py
  llm/app/services/user_reservation_service.py
  src/main/java/com/header/header/domain/chatbot/service/ChatbotService.java
  src/main/java/com/header/header/domain/reservation/service/BossReservationChatbotService.java
Labels: enhancement

#290 [FIX] #289 Add Encoding Config To The Dockerfile
  Dockerfile
Labels: bug

#297 [FEATURE] #296 Add WebMvcConfig
  nginx/conf.d/default.conf
  src/main/java/com/header/header/config/WebMvcConfig.java
Labels: enhancement

#303 [FIX] #302 Edit Redis Config - Redis 연결 환경 설정 개선 및 Docker 환경 대응
  llm/app/core/config.py
Labels: bug

#306 [FIX] #305 Add EC2 Environment Variable Redis Url
  .github/workflows/deploy.yml
Labels: bug

#309 [FIX] #308 Fix Edit Config.py - LLM Redis 설정 개선
  llm/app/core/config.py
Labels: bug

#310 [MERGE] master 브랜치 업데이트
  llm/app/core/config.py
Labels: merge

#312 [FIX] #311 Edit Config.py File
  llm/app/core/config.py
Labels: bug

#326 [FIX] #325 Fix BossReservation Error
  src/main/java/com/header/header/domain/reservation/dto/BossResvProjectionDTO.java
Labels: bug

#328 Create README.md
  README.md
Labels: documentation
